services:
  - type: web
    name: urban-24-7
    env: node
    plan: free
    buildCommand: cd client && npm install && npm run build && cd ../server && npm install
    startCommand: cd server && node server.js
    envVars:
      - key: PORT
        value: 10000
